export const taxExemptionReasons = [
  { value: "M00", label: "M00 - Regime Transitório" },
  { value: "M02", label: "M02 - Transmissão de bens e serviço não sujeita" },
  { value: "M04", label: "M04 - IVA - Regime de não Sujeição" },
  { value: "M11", label: "M11 - Isento Artigo 12.º b) do CIVA" },
  { value: "M12", label: "M12 - Isento Artigo 12.º c) do CIVA" },
  { value: "M13", label: "M13 - Isento Artigo 12.º d) do CIVA" },
  { value: "M14", label: "M14 - Isento Artigo 12.º e) do CIVA" },
  { value: "M15", label: "M15 - Isento Artigo 12.º f) do CIVA" },
  { value: "M17", label: "M17 - Isento Artigo 12.º h) do CIVA" },
  { value: "M18", label: "M18 - Isento Artigo 12.º i) do CIVA" },
  { value: "M19", label: "M19 - Isento Artigo 12.º j) do CIVA" },
  { value: "M20", label: "M20 - Isento Artigo 12.º k) do CIVA" },
  { value: "M30", label: "M30 - Isento Artigo 15.º 1 a) do CIVA" },
  { value: "M31", label: "M31 - Isento Artigo 15.º 1 b) do CIVA" },
  { value: "M32", label: "M32 - Isento Artigo 15.º 1 c) do CIVA" },
  { value: "M33", label: "M33 - Isento Artigo 15.º 1 d) do CIVA" },
  { value: "M34", label: "M34 - Isento Artigo 15.º 1 e) do CIVA" },
  { value: "M35", label: "M35 - Isento Artigo 15.º 1 f) do CIVA" },
  { value: "M36", label: "M36 - Isento Artigo 15.º 1 g) do CIVA" },
  { value: "M37", label: "M37 - Isento Artigo 15.º 1 h) do CIVA" },
  { value: "M38", label: "M38 - Isento Artigo 15.º 1 i) do CIVA" },
];
