name: CI

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:
  validate:
    name: Validation
    uses: ./.github/workflows/reusable-validate.yml
