name: Security Analysis

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '0 4 * * 1' # Todas as segundas-feiras às 04:00 UTC

permissions:
  contents: read
  security-events: write

jobs:
  codeql:
    name: CodeQL Static Security Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
